# Generated by Django 3.1.3 on 2020-11-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201112_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='langauge',
            new_name='language',
        ),
        migrations.AddField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False),
        ),
    ]
